import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarPublic from "@/components/NavbarPublic";
import { AuthProvider } from "./contexts/authContext";
import { CompanyProvider } from "./contexts/companyContext";
import { AppBootstrap } from "./components/appBootstrap";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <CompanyProvider>
            <AppBootstrap>
              <div className="min-h-screen font-sans text-black">
                <NavbarPublic />
                <AuthProvider>{children}</AuthProvider>
              </div>
            </AppBootstrap>
          </CompanyProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
