import type { Metadata } from "next";
import SideBar from "@/components/Sidebar";
import { Building2, LayoutDashboard, Receipt, UsersRound } from "lucide-react";
import Footer from "@/components/Footer";
import { MenuItem } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu: MenuItem[] = [
    {
      label: "Home",
      path: "/admin/",
      icon: LayoutDashboard,
    },
    {
      label: "Empresas",
      path: "/admin/companies",
      icon: Building2,
    },
    {
      label: "Usuarios y Permisos",
      path: "/admin/users",
      icon: UsersRound,
    },
    {
      label: "Facturación",
      path: "/admin/billing",
      icon: Receipt,
    },
  ];

  return (
    <main className="flex flex-col max-h-screen">
      <div className="grid grid-cols-12 gap-1 h-screen">
        <div className="bg-pink-600 col-span-2">
          <SideBar menuItems={menu} />
        </div>
        <div className="bg-white col-span-10">{children}</div>
      </div>
      <Footer />
    </main>
  );
}
