import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "@/components/Sidebar";
import {
  CalendarClock,
  Car,
  ClipboardList,
  LayoutDashboard,
  Receipt,
  Route,
  UserRound,
  Users,
} from "lucide-react";
import Footer from "@/components/Footer";
import { MenuItem } from "@/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu: MenuItem[] = [
    {
      label: "Home",
      path: "/company/",
      icon: LayoutDashboard,
    },
    {
      label: "Recorridos y Paradas",
      path: "/company/routes",
      icon: Route,
    },
    {
      label: "Servicios",
      path: "/company/services",
      icon: CalendarClock,
    },
    {
      label: "Conductores",
      path: "/company/drivers",
      icon: Users,
    },
    {
      label: "Pasajeros",
      path: "/company/passengers",
      icon: UserRound,
    },
    {
      label: "Lista de Pasajeros",
      path: "/company/passengerLists",
      icon: ClipboardList,
    },
    {
      label: "Facturación",
      path: "/company/billing",
      icon: Receipt,
    },
    {
      label: "Parque Móvil",
      path: "/company/vehicles",
      icon: Car,
    },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="flex flex-col max-h-screen">
          <div className="grid grid-cols-12 gap-1 h-screen">
            <div className="bg-pink-600 col-span-2">
              <SideBar menuItems={menu} />
            </div>
            <div className="bg-white col-span-10">{children}</div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
