FROM node:24-slim

WORKDIR /app

ENV NODE_ENV=development

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
COPY .env.dev .env

RUN pnpm prisma generate

EXPOSE 4001
CMD ["pnpm", "run", "dev"]
